services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    env_file:
      - ../.env
    ports:
      - ${API_PORT}:8000
    command: "uvicorn --factory application.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ../app/.:/app/